[providers]
nodejs = "18"
php = "8.2"

[phases.setup]
nixPkgs = ["nodejs", "npm", "php82", "php82Packages.composer", "php82Extensions.pdo_mysql", "php82Extensions.mysqli"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[phases.deploy]
cmds = [
    "php artisan migrate --force",
    "php artisan db:seed --force --class=UserSeeder"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
