const Ziggy = {
  url: 'http:\/\/localhost',
  port: null,
  defaults: {},
  routes: {
    'sanctum.csrf-cookie': {
      uri: 'sanctum\/csrf-cookie',
      methods: ['GET', 'HEAD'],
    },
    dashboard: { uri: 'dashboard', methods: ['GET', 'HEAD'] },
    workflow: { uri: 'workflow', methods: ['GET', 'HEAD'] },
    'workflow.take': {
      uri: 'workflow\/take\/{pinjaman}',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'workflow.release': {
      uri: 'workflow\/release\/{pinjaman}',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'workflow.advance': {
      uri: 'workflow\/advance\/{pinjaman}',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'workflow.return': {
      uri: 'workflow\/return\/{pinjaman}',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'workflow.decide': {
      uri: 'workflow\/decide\/{pinjaman}',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'profile.edit': { uri: 'profile', methods: ['GET', 'HEAD'] },
    'profile.update': { uri: 'profile', methods: ['PATCH'] },
    'profile.destroy': { uri: 'profile', methods: ['DELETE'] },
    'pinjaman.index': { uri: 'pinjaman', methods: ['GET', 'HEAD'] },
    'pinjaman.create': { uri: 'pinjaman\/create', methods: ['GET', 'HEAD'] },
    'pinjaman.create.wizard': {
      uri: 'pinjaman\/create\/wizard',
      methods: ['GET', 'HEAD'],
    },
    'pinjaman.create.wizard-new': {
      uri: 'pinjaman\/create\/wizard-new',
      methods: ['GET', 'HEAD'],
    },
    'pinjaman.store': { uri: 'pinjaman', methods: ['POST'] },
    'pinjaman.store.wizard': { uri: 'pinjaman\/wizard', methods: ['POST'] },
    'pinjaman.take': {
      uri: 'pinjaman\/{pinjaman}\/take',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.release': {
      uri: 'pinjaman\/{pinjaman}\/release',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.advance': {
      uri: 'pinjaman\/{pinjaman}\/advance',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.return': {
      uri: 'pinjaman\/{pinjaman}\/return',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.decide': {
      uri: 'pinjaman\/{pinjaman}\/decide',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.show': {
      uri: 'pinjaman\/{pinjaman}',
      methods: ['GET', 'HEAD'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.edit': {
      uri: 'pinjaman\/{pinjaman}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.update': {
      uri: 'pinjaman\/{pinjaman}',
      methods: ['PUT'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.destroy': {
      uri: 'pinjaman\/{pinjaman}',
      methods: ['DELETE'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.workflow-action': {
      uri: 'pinjaman\/{pinjaman}\/workflow-action',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.lock': {
      uri: 'pinjaman\/{pinjaman}\/lock',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.upload-ojk': {
      uri: 'pinjaman\/{pinjaman}\/upload-ojk',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.admin-decision': {
      uri: 'pinjaman\/{pinjaman}\/admin-decision',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.assign-analis': {
      uri: 'pinjaman\/{pinjaman}\/assign-analis',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.upload-lapangan': {
      uri: 'pinjaman\/{pinjaman}\/upload-lapangan',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.finish-analysis': {
      uri: 'pinjaman\/{pinjaman}\/finish-analysis',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'pinjaman.final-decision': {
      uri: 'pinjaman\/{pinjaman}\/final-decision',
      methods: ['POST'],
      parameters: ['pinjaman'],
      bindings: { pinjaman: 'id' },
    },
    'berkas.download': {
      uri: 'berkas\/{berkas}\/download',
      methods: ['GET', 'HEAD'],
      parameters: ['berkas'],
      bindings: { berkas: 'id' },
    },
    'berkas.view': {
      uri: 'berkas\/{berkas}\/view',
      methods: ['GET', 'HEAD'],
      parameters: ['berkas'],
      bindings: { berkas: 'id' },
    },
    'berkas.delete': {
      uri: 'berkas\/{berkas}',
      methods: ['DELETE'],
      parameters: ['berkas'],
      bindings: { berkas: 'id' },
    },
    'users.index': { uri: 'users', methods: ['GET', 'HEAD'] },
    'users.create': { uri: 'users\/create', methods: ['GET', 'HEAD'] },
    'users.store': { uri: 'users', methods: ['POST'] },
    'users.show': {
      uri: 'users\/{user}',
      methods: ['GET', 'HEAD'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'users.edit': {
      uri: 'users\/{user}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'users.update': {
      uri: 'users\/{user}',
      methods: ['PUT', 'PATCH'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'users.destroy': {
      uri: 'users\/{user}',
      methods: ['DELETE'],
      parameters: ['user'],
      bindings: { user: 'id' },
    },
    'nasabah.index': { uri: 'nasabah', methods: ['GET', 'HEAD'] },
    'nasabah.create': { uri: 'nasabah\/create', methods: ['GET', 'HEAD'] },
    'nasabah.store': { uri: 'nasabah', methods: ['POST'] },
    'nasabah.show': {
      uri: 'nasabah\/{nasabah}',
      methods: ['GET', 'HEAD'],
      parameters: ['nasabah'],
      bindings: { nasabah: 'id' },
    },
    'nasabah.edit': {
      uri: 'nasabah\/{nasabah}\/edit',
      methods: ['GET', 'HEAD'],
      parameters: ['nasabah'],
      bindings: { nasabah: 'id' },
    },
    'nasabah.update': {
      uri: 'nasabah\/{nasabah}',
      methods: ['PUT', 'PATCH'],
      parameters: ['nasabah'],
      bindings: { nasabah: 'id' },
    },
    'nasabah.destroy': {
      uri: 'nasabah\/{nasabah}',
      methods: ['DELETE'],
      parameters: ['nasabah'],
      bindings: { nasabah: 'id' },
    },
    'reports.index': { uri: 'reports', methods: ['GET', 'HEAD'] },
    'reports.export': { uri: 'reports\/export', methods: ['POST'] },
    register: { uri: 'register', methods: ['GET', 'HEAD'] },
    login: { uri: 'login', methods: ['GET', 'HEAD'] },
    'password.request': { uri: 'forgot-password', methods: ['GET', 'HEAD'] },
    'password.email': { uri: 'forgot-password', methods: ['POST'] },
    'password.reset': {
      uri: 'reset-password\/{token}',
      methods: ['GET', 'HEAD'],
      parameters: ['token'],
    },
    'password.store': { uri: 'reset-password', methods: ['POST'] },
    'verification.notice': { uri: 'verify-email', methods: ['GET', 'HEAD'] },
    'verification.verify': {
      uri: 'verify-email\/{id}\/{hash}',
      methods: ['GET', 'HEAD'],
      parameters: ['id', 'hash'],
    },
    'verification.send': {
      uri: 'email\/verification-notification',
      methods: ['POST'],
    },
    'password.confirm': { uri: 'confirm-password', methods: ['GET', 'HEAD'] },
    'password.update': { uri: 'password', methods: ['PUT'] },
    logout: { uri: 'logout', methods: ['POST'] },
    'storage.local': {
      uri: 'storage\/{path}',
      methods: ['GET', 'HEAD'],
      wheres: { path: '.*' },
      parameters: ['path'],
    },
  },
};
if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
  Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
